baseURL = "https://heapspace.rs/"
languageCode = "en-us"
title = "Heapspace"
disableRss = true
DefaultContentLanguage = "rs"

[languages]
  [languages.rs]
  [languages.en]

[[languages.en.menu.main]]
	identifier = "about"
	name = "about"
	url = "/en/about"
	weight = -110

[[languages.en.menu.main]]
	identifier = "events"
	name = "events"
	url = "/en/events"
	weight = -100

[[languages.en.menu.main]]
	identifier = "manifest"
	name = "manifest"
	url = "/manifest"
	weight = -90

[[languages.en.menu.main]]
	identifier = "contact"
	name = "contact"
	url = "#contact"
	weight = -80

[[menu.main]]
	identifier = "about"
	name = "o zajednici"
	url = "/o-zajednici"
	weight = -110

[[menu.main]]
	identifier = "events"
	name = "dogadjaji"
	url = "/dogadjaji"
	weight = -100

[[menu.main]]
	identifier = "manifest"
	name = "manifest"
	url = "/manifest"
	weight = -90

[[menu.main]]
	identifier = "contact"
	name = "kontakt"
	url = "#contact"
	weight = -80
