[[main]]
	identifier = "about"
	name = "about"
	url = "/en/about"
	weight = -110

[[main]]
	identifier = "events"
	name = "events"
	url = "/en/events"
	weight = -100

[[main]]
	identifier = "manifest"
	name = "manifest"
	url = "/manifest"
	weight = -90

[[main]]
	identifier = "contact"
	name = "contact"
	url = "#contact"
	weight = -80
