[[main]]
	identifier = "projects"
	name = "projekti"
	url = "/projekti"
	weight = -110

[[main]]
	identifier = "news"
	name = "novosti"
	url = "/novosti"
	weight = -100

[[main]]
	identifier = "manifest"
	name = "manifest"
	url = "/manifest"
	weight = -90

[[main]]
	identifier = "team"
	name = "tim"
	url = "/tim"
	weight = -80

[[main]]
	identifier = "contact"
	name = "kontakt"
	url = "/kontakt"
	weight = -70
