[[main]]
	identifier = "projects"
	name = "projects"
	url = "/en/projects"
	weight = -110

[[main]]
	identifier = "news"
	name = "news"
	url = "/en/news"
	weight = -100

[[main]]
	identifier = "manifest"
	name = "manifest"
	url = "/manifest"
	weight = -90

[[main]]
	identifier = "team"
	name = "team"
	url = "/team"
	weight = -80

[[main]]
	identifier = "contact"
	name = "contact"
	url = "/contact"
	weight = -70
